# Generated by Django 5.1.3 on 2024-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Oturum Başlatma'), ('LOGOUT', 'Oturum Sonlandırma')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
