# Generated by Django 5.1.3 on 2024-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], max_length=50)),
                ('reason', models.CharField(choices=[('ANNUAL', 'Yıllık İzin'), ('RELOCATION', 'Taşınma İzni'), ('SICK', 'Hastalık İzni'), ('DEATH_OF_CHILD_OR_SPOUSE', 'Çocuk veya Eşin Vefatı'), ('DEATH_OF_MOM_DAD_OR_SIBLING', 'Anne, Baba veya Kardeşin Vefatı'), ('DEATH_OF_SPOUSE_MOM_DAD_SIBLING', 'Eş, Anne, Baba veya Kardeşin Vefatı'), ('BIRTH_DAY', 'Doğum Günü İzni'), ('SPOUSE_BIRTH_DAY', 'Eşin Doğum Günü İzni'), ('COMPASSIONATE_LEAVE', 'Mazaret İzni'), ('MILITARY_LEAVE', 'Askerlik İzni'), ('MATERNITY_LEAVE', 'Süt İzni'), ('FREE_LEAVE', 'Ücretsiz İzin'), ('MARRIAGE_LEAVE', 'Düğün İzni')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
